[pytest]
addopts = -s -v
markers =
    gateway: Mark for gateway service tests.
    operations: Mark for operations service tests.
    regression: Mark for regression tests.
pythonpath =
    .
    protos/gen